# Generated by Django 6.0 on 2026-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(default='Curso no especificado', max_length=200)),
                ('institucion', models.CharField(default='Institución no especificada', max_length=200)),
                ('horas', models.CharField(default='0 horas', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cursos y Formaciones',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='Nombre no especificado', max_length=100)),
                ('apellidos', models.CharField(default='Apellido no especificado', max_length=100)),
                ('descripcion_perfil', models.TextField(default='Sin descripción de perfil')),
                ('cedula', models.CharField(default='000000000000', max_length=12)),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=50)),
                ('lugar_nacimiento', models.CharField(default='No especificado', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(default='No especificado', max_length=20)),
                ('estado_civil', models.CharField(default='Soltero/a', max_length=50)),
                ('licencia', models.CharField(default='Nula', max_length=50)),
                ('telefono', models.CharField(default='0000000000', max_length=20)),
                ('direccion', models.CharField(default='Dirección no especificada', max_length=500)),
                ('sitio_web', models.URLField(blank=True, default='')),
                ('email', models.EmailField(default='ejemplo@correo.com', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='EstudioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título no especificado', max_length=200)),
                ('institucion', models.CharField(default='Institución no especificada', max_length=200)),
                ('fecha_inicio', models.CharField(default='Fecha de inicio', max_length=50)),
                ('fecha_fin', models.CharField(default='Fecha de finalización', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estudios Realizados',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Cargo no especificado', max_length=150)),
                ('empresa', models.CharField(default='Empresa no especificada', max_length=150)),
                ('fecha_inicio', models.CharField(default='Fecha de inicio', max_length=50)),
                ('fecha_fin', models.CharField(default='Actualidad', max_length=50)),
                ('descripcion', models.TextField(default='Sin descripción de funciones')),
                ('ubicacion', models.CharField(default='Ubicación no especificada', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Experiencias Laborales',
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Producto no especificado', max_length=200)),
                ('descripcion', models.TextField(default='Sin descripción del producto')),
                ('fecha', models.CharField(default='Fecha de entrega', max_length=50)),
                ('registro_id', models.CharField(default='ID-000', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Productos Laborales',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Reconocimiento no especificado', max_length=200)),
                ('institucion', models.CharField(default='Institución no especificada', max_length=200)),
                ('fecha', models.CharField(default='Fecha no especificada', max_length=50)),
                ('codigo_registro', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Reconocimientos y Premios',
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(default='Producto en venta', max_length=150)),
                ('estado', models.CharField(default='Como nuevo', max_length=50)),
                ('descripcion', models.TextField(default='Sin descripción del artículo')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item_id', models.CharField(default='ITEM-000', max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Venta de Garaje',
            },
        ),
    ]
