# Generated by Django 6.0 on 2026-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_datospersonales_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/'),
        ),
    ]
