# Generated by Django 6.0 on 2026-01-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_ventagarage_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiorealizado',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube aquí el diploma o certificado en formato PDF', null=True, upload_to='educacion/certificados/'),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_fin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_inicio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
