# Generated by Django 6.0 on 2026-01-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_estudiorealizado_certificado_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube aquí el diploma o certificado en formato PDF', null=True, upload_to='educacion/certificados/'),
        ),
    ]
