# Generated by Django 6.0 on 2026-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_cursocapacitacion_certificado_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube el certificado del curso en formato PDF', null=True, upload_to='cursos/certificados/'),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='horas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='nombre_curso',
            field=models.CharField(max_length=200),
        ),
    ]
