# Generated by Django 6.0 on 2026-01-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_cursocapacitacion_certificado_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productolaboral',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube aquí la documentación o el archivo del proyecto (PDF recomendado)', null=True, upload_to='proyectos/archivos/'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='registro_id',
            field=models.CharField(max_length=50),
        ),
    ]
