# Generated by Django 6.0 on 2026-01-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_productolaboral_archivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'verbose_name_plural': 'Venta de Garage'},
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de unidades disponibles'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Como Nuevo', 'Como Nuevo'), ('Usado', 'Usado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='venta/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='item_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombre_producto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
