# Generated by Django 6.0 on 2026-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_ventagarage_options_ventagarage_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'verbose_name': 'Datos Personales', 'verbose_name_plural': 'Datos Personales'},
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='direccion_trabajo',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Laboral'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefono_convencional',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_github',
            field=models.URLField(blank=True, null=True, verbose_name='URL GitHub'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='URL Instagram'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='URL TikTok'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='URL YouTube'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='URL LinkedIn'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='cedula',
            field=models.CharField(max_length=13, verbose_name='Cédula / ID'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion_perfil',
            field=models.TextField(blank=True, null=True, verbose_name='Perfil Profesional (Bio)'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion',
            field=models.TextField(verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(choices=[('Soltera/o', 'Soltera/o'), ('Casada/o', 'Casada/o'), ('Divorciada/o', 'Divorciada/o'), ('Viuda/o', 'Viuda/o'), ('Unión Libre', 'Unión Libre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Licencia de Conducir'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono Celular'),
        ),
    ]
