# Generated by Django 5.2 on 2026-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_datospersonales_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimiento',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube el certificado del reconocimiento en formato PDF', null=True, upload_to='reconocimientos/certificados/'),
        ),
    ]
